In [3]:
import pandas as pd
df = pd.read_csv('data.csv')
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State_gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self_emp_not_inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [4]:
def race_count():
    # Count the number of people of each race
    return df['race'].value_counts()

def average_age_men():
    # Filter by male and calculate the average age
    return round(df[df['sex'] == 'Male']['age'].mean(), 1)

def percentage_bachelors():
    # Percentage of people with a Bachelor's degree
    bachelors_count = df[df['education'] == 'Bachelors'].shape[0]
    total_count = df.shape[0]
    return round((bachelors_count / total_count) * 100, 1)

def percentage_advanced_education_rich():
    # Percentage of people with advanced education (Bachelors, Masters, Doctorate) who earn >50K
    advanced_education = df[df['education'].isin(['Bachelors', 'Masters', 'Doctorate'])]
    rich_advanced_education = advanced_education[advanced_education['salary'] == '>50K']
    return round((rich_advanced_education.shape[0] / advanced_education.shape[0]) * 100, 1)

def percentage_without_advanced_education_rich():
    # Percentage of people without advanced education who earn >50K
    no_advanced_education = df[~df['education'].isin(['Bachelors', 'Masters', 'Doctorate'])]
    rich_no_advanced_education = no_advanced_education[no_advanced_education['salary'] == '>50K']
    return round((rich_no_advanced_education.shape[0] / no_advanced_education.shape[0]) * 100, 1)

def minimum_hours():
    # Minimum number of hours worked per week
    return df['hours-per-week'].min()

def percentage_min_workers_rich():
    # Percentage of people who work the minimum hours per week and earn >50K
    min_hours = df['hours-per-week'].min()
    min_workers = df[df['hours-per-week'] == min_hours]
    rich_min_workers = min_workers[min_workers['salary'] == '>50K']
    return round((rich_min_workers.shape[0] / min_workers.shape[0]) * 100, 1)

def country_with_highest_earning_percentage():
    # Country with the highest percentage of people earning >50K
    country_group = df.groupby('native-country')
    rich_percentage_by_country = country_group.apply(
        lambda x: (x[x['salary'] == '>50K'].shape[0] / x.shape[0]) * 100
    )
    highest_country = rich_percentage_by_country.idxmax()
    highest_percentage = round(rich_percentage_by_country.max(), 1)
    return highest_country, highest_percentage

def most_popular_occupation_in_india():
    # Most popular occupation for people earning >50K in India
    india_rich = df[(df['native-country'] == 'India') & (df['salary'] == '>50K')]
    return india_rich['occupation'].mode()[0]

# Testing the functions
if __name__ == "__main__":
    print(race_count())
    print(average_age_men())
    print(percentage_bachelors())
    print(percentage_advanced_education_rich())
    print(percentage_without_advanced_education_rich())
    print(minimum_hours())
    print(percentage_min_workers_rich())
    print(country_with_highest_earning_percentage())
    print(most_popular_occupation_in_india())

race
White    3
Black    2
Name: count, dtype: int64
45.0
60.0
0.0
0.0
13
0.0
('Cuba', np.float64(0.0))

C:\Users\Administrator\AppData\Local\Temp\ipykernel_9340\531573821.py:41: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  rich_percentage_by_country = country_group.apply(

KeyError: 0